"""Structured prompt templates for MedGemma narrative generation.

Implements ADR-003 prompt architecture: fixed system prompt, structured user
prompt assembled from domain model data, and safety disclaimers.
"""

from __future__ import annotations

from digital_twin_tumor.domain.models import (
    GrowthModelResult,
    Measurement,
    RECISTResponse,
    SimulationResult,
    TherapyEvent,
    UncertaintyEstimate,
)

# ---------------------------------------------------------------------------
# Fixed constants
# ---------------------------------------------------------------------------

SYSTEM_PROMPT: str = (
    "You are a medical image analysis research assistant. You analyze tumor "
    "measurement data and growth model results for RESEARCH PURPOSES ONLY. "
    "You MUST NOT provide clinical recommendations, treatment advice, or "
    "diagnostic conclusions. Always state that findings require clinical "
    "validation. Never use phrases like 'I recommend', 'prescribe', "
    "'diagnose', or 'you should'."
)

DISCLAIMER: str = (
    "DISCLAIMER: This analysis is generated by an AI system for research "
    "purposes only. It is NOT intended to guide clinical treatment decisions. "
    "All findings must be reviewed and validated by qualified medical "
    "professionals."
)

# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------


def build_measurement_table(measurements: list[Measurement]) -> str:
    """Format measurements as a markdown table.

    Parameters
    ----------
    measurements:
        Ordered list of :class:`Measurement` instances.

    Returns
    -------
    str
        Markdown table with columns: Timepoint | Date | Diameter (mm) |
        Volume (mm^3) | Method.
    """
    if not measurements:
        return "No measurement data available."

    lines: list[str] = [
        "| Timepoint | Date | Diameter (mm) | Volume (mm\u00b3) | Method |",
        "|-----------|------|---------------|---------------|--------|",
    ]
    for idx, m in enumerate(measurements, start=1):
        date_str = m.timestamp.strftime("%Y-%m-%d") if m.timestamp else "N/A"
        lines.append(
            f"| {idx} | {date_str} | {m.diameter_mm:.1f} "
            f"| {m.volume_mm3:.1f} | {m.method} |"
        )
    return "\n".join(lines)


def build_therapy_timeline(events: list[TherapyEvent]) -> str:
    """Format therapy events as a human-readable timeline.

    Parameters
    ----------
    events:
        Ordered list of :class:`TherapyEvent` instances.

    Returns
    -------
    str
        Bulleted timeline of therapy events.
    """
    if not events:
        return "No therapy events recorded."

    lines: list[str] = []
    for ev in events:
        start = ev.start_date.isoformat() if ev.start_date else "unknown"
        end = ev.end_date.isoformat() if ev.end_date else "ongoing"
        dose_info = f" (dose: {ev.dose})" if ev.dose else ""
        lines.append(f"- {start} to {end}: {ev.therapy_type}{dose_info}")
    return "\n".join(lines)


def build_uncertainty_summary(estimate: UncertaintyEstimate) -> str:
    """Render an uncertainty estimate as readable text.

    Parameters
    ----------
    estimate:
        The combined :class:`UncertaintyEstimate`.

    Returns
    -------
    str
        Multi-line description of measurement uncertainty.
    """
    lines: list[str] = [
        f"Total measurement uncertainty (1 sigma): {estimate.total_sigma:.2f} mm",
        f"  - Manual measurement sigma:  {estimate.sigma_manual:.2f} mm",
        f"  - Automated measurement sigma: {estimate.sigma_auto:.2f} mm",
        f"  - Scanner variability sigma:  {estimate.sigma_scan:.2f} mm",
        f"Reliability classification: {estimate.reliability}",
    ]
    return "\n".join(lines)


def build_growth_model_summary(results: list[GrowthModelResult]) -> str:
    """Summarise growth model fitting results.

    Parameters
    ----------
    results:
        List of :class:`GrowthModelResult` from competing models.

    Returns
    -------
    str
        Summary including model names, AIC weights, selected model, and key
        parameters.
    """
    if not results:
        return "No growth model results available."

    # Sort by Akaike weight descending to find the best model.
    ranked = sorted(results, key=lambda r: r.akaike_weight, reverse=True)
    best = ranked[0]

    lines: list[str] = ["Growth model comparison:"]
    for r in ranked:
        param_str = ", ".join(f"{k}={v:.4g}" for k, v in r.parameters.items())
        lines.append(
            f"  - {r.model_name}: AIC weight={r.akaike_weight:.3f}, "
            f"AIC={r.aic:.1f}, BIC={r.bic:.1f}"
        )
        if param_str:
            lines.append(f"    Parameters: {param_str}")

    lines.append(f"\nSelected model: {best.model_name} "
                 f"(Akaike weight {best.akaike_weight:.3f})")
    return "\n".join(lines)


def build_counterfactual_summary(simulations: list[SimulationResult]) -> str:
    """Summarise what-if simulation scenarios for comparison.

    Parameters
    ----------
    simulations:
        List of :class:`SimulationResult` instances.

    Returns
    -------
    str
        Comparison table of scenario outcomes.
    """
    if not simulations:
        return "No simulation scenarios available."

    lines: list[str] = ["Counterfactual simulation results:"]
    for sim in simulations:
        n_points = len(sim.time_points) if sim.time_points.size > 0 else 0
        final_vol = (
            f"{sim.predicted_volumes[-1]:.1f}"
            if sim.predicted_volumes.size > 0
            else "N/A"
        )
        final_lower = (
            f"{sim.lower_bound[-1]:.1f}" if sim.lower_bound.size > 0 else "N/A"
        )
        final_upper = (
            f"{sim.upper_bound[-1]:.1f}" if sim.upper_bound.size > 0 else "N/A"
        )
        param_str = ", ".join(f"{k}={v:.4g}" for k, v in sim.parameters.items())
        lines.append(f"  Scenario: {sim.scenario_name}")
        lines.append(f"    Time points simulated: {n_points}")
        lines.append(
            f"    Final predicted volume: {final_vol} mm\u00b3 "
            f"(95% CI: {final_lower}\u2013{final_upper})"
        )
        if param_str:
            lines.append(f"    Parameters: {param_str}")
    return "\n".join(lines)


def build_recist_summary(responses: list[RECISTResponse]) -> str:
    """Summarise the RECIST 1.1 response trajectory.

    Parameters
    ----------
    responses:
        Ordered list of :class:`RECISTResponse` per time-point.

    Returns
    -------
    str
        Formatted trajectory showing category changes over time.
    """
    if not responses:
        return "No RECIST response data available."

    lines: list[str] = ["RECIST 1.1 response trajectory:"]
    for idx, r in enumerate(responses, start=1):
        confirmed_tag = " (confirmed)" if r.is_confirmed else " (unconfirmed)"
        lines.append(
            f"  Timepoint {idx}: {r.category}{confirmed_tag} | "
            f"Sum of diameters: {r.sum_of_diameters:.1f} mm | "
            f"Change from baseline: {r.percent_change_from_baseline:+.1f}% | "
            f"Change from nadir: {r.percent_change_from_nadir:+.1f}%"
        )
    return "\n".join(lines)


def compose_user_prompt(
    measurements: list[Measurement],
    therapy_events: list[TherapyEvent],
    growth_results: list[GrowthModelResult],
    simulations: list[SimulationResult],
    uncertainty: UncertaintyEstimate,
    recist_responses: list[RECISTResponse],
) -> str:
    """Assemble the full structured user prompt from all data sections.

    Parameters
    ----------
    measurements:
        Longitudinal tumor measurements.
    therapy_events:
        Therapy administration events.
    growth_results:
        Growth model fitting results.
    simulations:
        What-if simulation results.
    uncertainty:
        Combined measurement uncertainty.
    recist_responses:
        RECIST 1.1 response classifications.

    Returns
    -------
    str
        Complete user prompt ready for the language model.
    """
    sections: list[str] = [
        "## Tumor Measurement Data",
        build_measurement_table(measurements),
        "",
        "## Therapy Timeline",
        build_therapy_timeline(therapy_events),
        "",
        "## Growth Model Analysis",
        build_growth_model_summary(growth_results),
        "",
        "## Counterfactual Simulations",
        build_counterfactual_summary(simulations),
        "",
        "## Measurement Uncertainty",
        build_uncertainty_summary(uncertainty),
        "",
        "## RECIST 1.1 Response Assessment",
        build_recist_summary(recist_responses),
        "",
        "---",
        "Based on the data above, provide a structured research summary that:",
        "1. Describes the observed tumor trajectory over time.",
        "2. Summarizes the growth model fit and its implications.",
        "3. Compares the counterfactual simulation scenarios.",
        "4. Notes measurement uncertainty and its impact on conclusions.",
        "5. States the RECIST response trajectory.",
        "6. Clearly states that all findings require clinical validation.",
    ]
    return "\n".join(sections)
