"""Prompt templates and context builders for MedGemma reasoning.

Provides structured prompt constants and helper functions that format
patient data into prompt-ready text for the MedGemma reasoning layer.
All prompts emphasize non-clinical research use, evidence grounding,
and uncertainty awareness per MedGemma safety guidelines.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SYSTEM_PROMPT: str = (
    "You are a medical AI assistant powered by MedGemma, part of Google's "
    "Health AI Developer Foundations (HAI-DEF). This system uses MedGemma, "
    "which is trained on medical text comprehension and medical imaging "
    "understanding to provide clinically grounded analysis. "
    "You are generating a tumor board summary for a digital twin research "
    "system. This is for RESEARCH PURPOSES ONLY, not clinical use. "
    "MedGemma is not intended for direct clinical decision-making. "
    "Ground all observations in the measured data provided. "
    "Acknowledge uncertainty where present. Never provide treatment "
    "recommendations or diagnostic conclusions. Never claim to diagnose "
    "or prescribe. Always state that findings require validation by "
    "qualified oncology professionals."
)

TUMOR_BOARD_TEMPLATE: str = (
    "Based on the following patient data from a digital twin tumor response "
    "assessment system, generate a structured tumor board research summary.\n\n"
    "{patient_context}\n\n"
    "{measurement_context}\n\n"
    "{therapy_context}\n\n"
    "{growth_context}\n\n"
    "{simulation_context}\n\n"
    "Please provide the following sections:\n"
    "1. **Clinical Summary**: Summarize the patient profile and disease status "
    "based on measured data.\n"
    "2. **Response Assessment**: Interpret the RECIST trajectory and what the "
    "measured changes indicate.\n"
    "3. **Trend Analysis**: Describe the longitudinal trend in tumor burden, "
    "referencing specific measurement values.\n"
    "4. **Uncertainty Discussion**: Discuss sources of uncertainty in the "
    "measurements and model predictions.\n"
    "5. **Key Findings**: List the most important observations from the data.\n\n"
    "Ground every claim in the numeric data provided. Do not speculate beyond "
    "what the data supports. State clearly that this is a research summary "
    "and not a clinical assessment."
)

COUNTERFACTUAL_TEMPLATE: str = (
    "The following counterfactual simulations were generated by a digital twin "
    "growth model system. These are hypothetical 'what-if' scenarios, NOT "
    "predictions of actual clinical outcomes.\n\n"
    "**Baseline trajectory:**\n{baseline_summary}\n\n"
    "**Counterfactual scenarios:**\n{counterfactual_summaries}\n\n"
    "**Therapy context:**\n{therapy_info}\n\n"
    "Please interpret these simulation results in clinical research language:\n"
    "1. Compare the counterfactual trajectories to the baseline.\n"
    "2. Discuss what the simulations suggest about treatment timing sensitivity.\n"
    "3. Note the uncertainty bounds and their implications.\n"
    "4. Emphasize that these are mathematical model outputs, not clinical "
    "predictions.\n"
    "5. State that treatment decisions must never be based on simulations alone."
)

IMAGING_ANALYSIS_TEMPLATE: str = (
    "You are analyzing a medical imaging slice from a tumor response assessment "
    "study. This is for RESEARCH PURPOSES ONLY.\n\n"
    "{context}\n\n"
    "Describe what is visible in this imaging slice. Focus on:\n"
    "1. Identifiable anatomical structures.\n"
    "2. Any visible lesions or abnormalities and their approximate location.\n"
    "3. Image quality observations.\n"
    "4. Relevant features for longitudinal tumor tracking.\n\n"
    "Do NOT provide diagnostic conclusions. State that findings require review "
    "by a qualified radiologist."
)

SAFETY_DISCLAIMER: str = (
    "DISCLAIMER: This analysis was generated by an AI research system using "
    "MedGemma, part of Google's Health AI Developer Foundations (HAI-DEF). "
    "This output is for RESEARCH AND EDUCATIONAL PURPOSES ONLY. It is NOT "
    "intended for clinical use, diagnosis, or treatment guidance. Per "
    "MedGemma's model card: the model is not intended for direct clinical "
    "use and should not be used to inform clinical decision-making without "
    "appropriate validation and oversight. All observations are derived from "
    "mathematical models and automated measurements that have not been "
    "clinically validated. Any clinical interpretation must be performed by "
    "qualified medical professionals. Do not make treatment decisions based "
    "on this output."
)


FHIR_CONTEXT_TEMPLATE: str = (
    "**Patient Data (FHIR-compatible structure):**\n\n"
    "```\n"
    "Resource: Patient\n"
    "  identifier: {patient_id}\n"
    "  gender: {gender}\n"
    "  birthDate: {birth_date}\n\n"
    "Resource: Condition\n"
    "  code: {cancer_type}\n"
    "  stage: {stage}\n"
    "  clinicalStatus: active\n\n"
    "Resource: ImagingStudy\n"
    "  modality: {modality}\n"
    "  numberOfSeries: {num_series}\n"
    "  started: {study_date}\n"
    "  endpoint: [DICOMweb]\n\n"
    "Resource: Observation (tumor-measurement)\n"
    "  code: RECIST 1.1 Sum of Diameters\n"
    "  valueQuantity: {sum_of_diameters} mm\n"
    "  effectiveDateTime: {observation_date}\n"
    "  interpretation: {recist_category}\n\n"
    "Resource: MedicationAdministration\n"
    "  medicationCodeableConcept: {drug_name}\n"
    "  effectivePeriod: {start_date} to {end_date}\n"
    "  dosage: {dose}\n"
    "```\n\n"
    "This data is structured to align with FHIR R4 resources for "
    "interoperability with clinical FHIR stores and EHR systems."
)


# ---------------------------------------------------------------------------
# Context builder helpers
# ---------------------------------------------------------------------------


def build_measurement_context(
    measurements: list[dict[str, Any]],
    recist_responses: list[dict[str, Any]],
    timepoints: list[dict[str, Any]],
) -> str:
    """Format measurement data into prompt-ready text.

    Builds a longitudinal measurement table showing week, sum of diameters,
    percent change from baseline, and RECIST category at each timepoint.

    Parameters
    ----------
    measurements:
        List of measurement dicts with keys like ``diameter_mm``,
        ``volume_mm3``, ``timepoint_id``, ``week``.
    recist_responses:
        List of RECIST response dicts with keys like ``category``,
        ``sum_of_diameters``, ``percent_change_from_baseline``.
    timepoints:
        List of timepoint dicts with keys like ``week``, ``scan_date``,
        ``therapy_status``.

    Returns
    -------
    str
        Formatted markdown text suitable for prompt inclusion.
    """
    if not measurements:
        return "**Measurements:** No measurement data available."

    lines: list[str] = [
        "**Longitudinal Measurement Data:**",
        "",
        "| Week | Sum of Diameters (mm) | % Change from Baseline | RECIST | Status |",
        "|------|-----------------------|------------------------|--------|--------|",
    ]

    # Build a week-to-timepoint index for matching RECIST responses
    tp_by_week: dict[float, dict[str, Any]] = {}
    for tp in timepoints:
        week = tp.get("week")
        if week is not None:
            tp_by_week[float(week)] = tp

    # Aggregate measurements by timepoint
    tp_sums: dict[str, float] = {}
    tp_weeks: dict[str, float] = {}
    for m in measurements:
        tp_id = m.get("timepoint_id", "")
        diam = float(m.get("diameter_mm", 0))
        tp_sums[tp_id] = tp_sums.get(tp_id, 0.0) + diam
        week = m.get("week")
        if week is not None:
            tp_weeks[tp_id] = float(week)

    # Sort by week
    sorted_tps = sorted(tp_weeks.items(), key=lambda x: x[1])

    for i, (tp_id, week) in enumerate(sorted_tps):
        sod = tp_sums.get(tp_id, 0.0)

        # Match RECIST response
        recist_cat = "N/A"
        pct_change = 0.0
        if i < len(recist_responses):
            r = recist_responses[i]
            recist_cat = r.get("category", "N/A")
            pct_change = float(r.get("percent_change_from_baseline", 0.0))

        # Match therapy status
        status = "N/A"
        tp_info = tp_by_week.get(week, {})
        if tp_info:
            status = tp_info.get("therapy_status", "N/A")

        lines.append(
            f"| {week:.0f} | {sod:.1f} | {pct_change:+.1f}% | {recist_cat} | {status} |"
        )

    # Add RECIST trajectory summary
    if recist_responses:
        cats = [r.get("category", "?") for r in recist_responses]
        lines.append(f"\n**RECIST Trajectory:** {' -> '.join(cats)}")

    # Add measurement count
    lines.append(
        f"\n**Total observations:** {len(measurements)} across "
        f"{len(sorted_tps)} timepoints."
    )

    return "\n".join(lines)


def build_therapy_context(therapy_events: list[dict[str, Any]]) -> str:
    """Format therapy events into prompt-ready text.

    Parameters
    ----------
    therapy_events:
        List of therapy event dicts with keys like ``therapy_type``,
        ``drug_name``, ``dose``, ``start_date``, ``end_date``.

    Returns
    -------
    str
        Formatted therapy timeline text.
    """
    if not therapy_events:
        return "**Treatment History:** No therapy events recorded."

    lines: list[str] = ["**Treatment History:**", ""]
    for ev in therapy_events:
        therapy_type = ev.get("therapy_type", "Unknown").title()
        drug = ev.get("drug_name", ev.get("dose", "N/A"))
        start = ev.get("start_date", "unknown")
        end = ev.get("end_date", "ongoing")
        lines.append(f"- **{therapy_type}:** {drug} ({start} to {end})")

    return "\n".join(lines)


def build_growth_context(growth_results: list[dict[str, Any]]) -> str:
    """Format growth model results into prompt-ready text.

    Parameters
    ----------
    growth_results:
        List of growth model result dicts with keys like ``model_name``,
        ``aic``, ``weight``.

    Returns
    -------
    str
        Formatted growth model ensemble text.
    """
    if not growth_results:
        return "**Growth Model Analysis:** No growth model results available."

    lines: list[str] = ["**Growth Model Ensemble:**", ""]

    # Sort by weight descending
    sorted_results = sorted(
        growth_results, key=lambda g: float(g.get("weight", 0)), reverse=True
    )

    for g in sorted_results:
        name = g.get("model_name", "Unknown")
        aic = float(g.get("aic", 0))
        weight = float(g.get("weight", 0))
        lines.append(f"- **{name}:** AIC = {aic:.1f}, Akaike weight = {weight:.3f}")

    best = sorted_results[0] if sorted_results else None
    if best:
        lines.append(
            f"\n**Best model:** {best.get('model_name', '?')} "
            f"(weight = {float(best.get('weight', 0)):.3f})"
        )

    return "\n".join(lines)
